export default [
  {
    id: 1,
    name: 'literacy',
    type: 'category',
    icon: null,
  }, {
    id: 2,
    name: 'politics',
    type: 'category',
    icon: null,
  }, {
    id: 3,
    name: 'technology',
    type: 'category',
    icon: null,
  }, {
    id: 4,
    name: 'music',
    type: 'category',
    icon: null,
  }, {
    id: 5,
    name: 'finance',
    type: 'category',
    icon: null,
  }, {
    id: 6,
    name: 'entrepreneurs',
    type: 'community',
    icon: 62,
  }, {
    id: 7,
    name: 'crypto-rich',
    type: 'community',
    icon: 61,
  }, {
    id: 8,
    name: 'healthy-life',
    type: 'community',
    icon: 60,
  }, {
    id: 9,
    name: 'motorcycles',
    type: 'category',
    icon: null,
  }, {
    id: 10,
    name: 'relationships',
    type: 'category',
    icon: null,
  }, {
    id: 11,
    name: 'human-nature',
    type: 'category',
    icon: null,
  }, {
    id: 12,
    name: 'news',
    type: 'category',
    icon: null,
  },
]